### ISSUE TITLE
Combination Potion - Lifeforce doesn't apply

### ISSUE THREAD

**Issue by Velosofy** [VoidRift/AutoPotion#4]
in any combination potion that has Lifeforce, it doesn't apply the effect
Tried:
- Battle Combination
- Tank Combination Vanilla
- Tank Combination w/ Calamity

**Comment by VoidRift** [comment]
Tested the Tank Combination Vanilla and Battle Combination potions with the mod AutoPotion disabled and it still does not increase health by 20% so it might be a problem AlchemistNPC mod.

Can you confirm on your side if the problem is still happening if the mod AutoPotion is disabled just to make sure?

**Comment by Velosofy** [comment]
Upon further testing - turns out AlchemistNPC is the problem.
I'll close the issue, thanks.
